Update skill-zhTW.json
urakagi/uma-clock-emu pull request #30
Opened 2023-02-09 16:21 UTC by reDustMistyRain

2023-02-09 17:05 UTC, reDustMistyRain commented
*有官方翻譯的用官方翻譯
*沒官方翻譯的使用wiki翻譯
*修正一條wiki翻譯：情人節雷恩固有
"あなたに捧げるフリーポア": "獻給你的雕花",
雕花->拉花
字面上是 フリーポア (free pour) 應指拉花，故修正

2023-02-10 05:47 UTC, urakagi commented
沒官方翻譯的請留空白，因為現行繁中版就有非官方翻譯散落各處不知道怎麼修的問題，留空白（並顯示日文）維護簡單很多

2023-02-10 05:48 UTC, urakagi requested changes
沒官方翻譯的請留空白，因為現行繁中版就有非官方翻譯散落各處不知道怎麼修的問題，留空白（並顯示日文）維護簡單很多

2023-02-10 05:56 UTC, reDustMistyRain commented
Got it~
沒問題，我去處理～

2023-02-10 06:01 UTC, reDustMistyRain commented
這樣應該沒問題了，有翻譯的都是gametora上面有譯名的，應該不會錯～
再麻煩幫我檢視一下，感謝！

2023-02-10 08:02 UTC, urakagi commented
OK 了，感謝

2023-02-10 08:02 UTC, urakagi approved these changes

2023-02-10 08:02 UTC, merged